steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-akap", "."]
    dir: "notes-backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-akap"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - notes-backend-akap
      - --image
      - gcr.io/$PROJECT_ID/be-akap
      - --timeout
      - 1000s
      - --port
      - "5001"
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME}

options:
  logging: CLOUD_LOGGING_ONLY
